//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.10.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from ./SdAsm.g4 by ANTLR 4.10.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using IParseTreeListener = Antlr4.Runtime.Tree.IParseTreeListener;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete listener for a parse tree produced by
/// <see cref="SdAsmParser"/>.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.10.1")]
[System.CLSCompliant(false)]
public interface ISdAsmListener : IParseTreeListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="SdAsmParser.asmFile"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAsmFile([NotNull] SdAsmParser.AsmFileContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SdAsmParser.asmFile"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAsmFile([NotNull] SdAsmParser.AsmFileContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SdAsmParser.codeLine"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCodeLine([NotNull] SdAsmParser.CodeLineContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SdAsmParser.codeLine"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCodeLine([NotNull] SdAsmParser.CodeLineContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SdAsmParser.directive"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDirective([NotNull] SdAsmParser.DirectiveContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SdAsmParser.directive"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDirective([NotNull] SdAsmParser.DirectiveContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SdAsmParser.moduleName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterModuleName([NotNull] SdAsmParser.ModuleNameContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SdAsmParser.moduleName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitModuleName([NotNull] SdAsmParser.ModuleNameContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SdAsmParser.sdccOpts"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSdccOpts([NotNull] SdAsmParser.SdccOptsContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SdAsmParser.sdccOpts"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSdccOpts([NotNull] SdAsmParser.SdccOptsContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SdAsmParser.segment"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSegment([NotNull] SdAsmParser.SegmentContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SdAsmParser.segment"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSegment([NotNull] SdAsmParser.SegmentContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SdAsmParser.segmentName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSegmentName([NotNull] SdAsmParser.SegmentNameContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SdAsmParser.segmentName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSegmentName([NotNull] SdAsmParser.SegmentNameContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SdAsmParser.segmentOpts"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSegmentOpts([NotNull] SdAsmParser.SegmentOptsContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SdAsmParser.segmentOpts"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSegmentOpts([NotNull] SdAsmParser.SegmentOptsContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SdAsmParser.bootAddr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBootAddr([NotNull] SdAsmParser.BootAddrContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SdAsmParser.bootAddr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBootAddr([NotNull] SdAsmParser.BootAddrContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SdAsmParser.memoryAlloc"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMemoryAlloc([NotNull] SdAsmParser.MemoryAllocContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SdAsmParser.memoryAlloc"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMemoryAlloc([NotNull] SdAsmParser.MemoryAllocContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SdAsmParser.memoryData"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMemoryData([NotNull] SdAsmParser.MemoryDataContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SdAsmParser.memoryData"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMemoryData([NotNull] SdAsmParser.MemoryDataContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SdAsmParser.ifStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIfStatement([NotNull] SdAsmParser.IfStatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SdAsmParser.ifStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIfStatement([NotNull] SdAsmParser.IfStatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SdAsmParser.label"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLabel([NotNull] SdAsmParser.LabelContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SdAsmParser.label"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLabel([NotNull] SdAsmParser.LabelContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SdAsmParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStatement([NotNull] SdAsmParser.StatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SdAsmParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStatement([NotNull] SdAsmParser.StatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SdAsmParser.absAddrAllocExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAbsAddrAllocExpr([NotNull] SdAsmParser.AbsAddrAllocExprContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SdAsmParser.absAddrAllocExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAbsAddrAllocExpr([NotNull] SdAsmParser.AbsAddrAllocExprContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SdAsmParser.instruction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterInstruction([NotNull] SdAsmParser.InstructionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SdAsmParser.instruction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitInstruction([NotNull] SdAsmParser.InstructionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SdAsmParser.expressions"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExpressions([NotNull] SdAsmParser.ExpressionsContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SdAsmParser.expressions"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExpressions([NotNull] SdAsmParser.ExpressionsContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SdAsmParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExpr([NotNull] SdAsmParser.ExprContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SdAsmParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExpr([NotNull] SdAsmParser.ExprContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SdAsmParser.operand"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterOperand([NotNull] SdAsmParser.OperandContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SdAsmParser.operand"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitOperand([NotNull] SdAsmParser.OperandContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SdAsmParser.operator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterOperator([NotNull] SdAsmParser.OperatorContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SdAsmParser.operator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitOperator([NotNull] SdAsmParser.OperatorContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SdAsmParser.arithmeticOperator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterArithmeticOperator([NotNull] SdAsmParser.ArithmeticOperatorContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SdAsmParser.arithmeticOperator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitArithmeticOperator([NotNull] SdAsmParser.ArithmeticOperatorContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SdAsmParser.unaryOperator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterUnaryOperator([NotNull] SdAsmParser.UnaryOperatorContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SdAsmParser.unaryOperator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitUnaryOperator([NotNull] SdAsmParser.UnaryOperatorContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SdAsmParser.assignmentOperator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAssignmentOperator([NotNull] SdAsmParser.AssignmentOperatorContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SdAsmParser.assignmentOperator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAssignmentOperator([NotNull] SdAsmParser.AssignmentOperatorContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SdAsmParser.bitOperator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBitOperator([NotNull] SdAsmParser.BitOperatorContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SdAsmParser.bitOperator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBitOperator([NotNull] SdAsmParser.BitOperatorContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SdAsmParser.compareOperator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCompareOperator([NotNull] SdAsmParser.CompareOperatorContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SdAsmParser.compareOperator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCompareOperator([NotNull] SdAsmParser.CompareOperatorContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SdAsmParser.logicalOperator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLogicalOperator([NotNull] SdAsmParser.LogicalOperatorContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SdAsmParser.logicalOperator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLogicalOperator([NotNull] SdAsmParser.LogicalOperatorContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SdAsmParser.normalLabel"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterNormalLabel([NotNull] SdAsmParser.NormalLabelContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SdAsmParser.normalLabel"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitNormalLabel([NotNull] SdAsmParser.NormalLabelContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SdAsmParser.inlineLabel"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterInlineLabel([NotNull] SdAsmParser.InlineLabelContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SdAsmParser.inlineLabel"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitInlineLabel([NotNull] SdAsmParser.InlineLabelContext context);
}
