//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.10.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from SdAsm.g4 by ANTLR 4.10.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using System;
using System.IO;
using System.Text;
using System.Diagnostics;
using System.Collections.Generic;
using Antlr4.Runtime;
using Antlr4.Runtime.Atn;
using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using DFA = Antlr4.Runtime.Dfa.DFA;

[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.10.1")]
[System.CLSCompliant(false)]
public partial class SdAsmParser : Parser {
	protected static DFA[] decisionToDFA;
	protected static PredictionContextCache sharedContextCache = new PredictionContextCache();
	public const int
		T__0=1, T__1=2, T__2=3, T__3=4, T__4=5, T__5=6, T__6=7, T__7=8, T__8=9, 
		T__9=10, T__10=11, T__11=12, T__12=13, Dot=14, LeftParen=15, RightParen=16, 
		LeftBracket=17, RightBracket=18, Less=19, LessEqual=20, Greater=21, GreaterEqual=22, 
		Equal=23, NotEqual=24, Minus=25, Plus=26, Star=27, Div=28, Mod=29, AndAnd=30, 
		OrOr=31, Not=32, LeftShift=33, RightShift=34, And=35, Or=36, Caret=37, 
		Tilde=38, Assign=39, PlusAssign=40, MinusAssign=41, StarAssign=42, DivAssign=43, 
		ModAssign=44, LeftShiftAssign=45, RightShiftAssign=46, AndAssign=47, OrAssign=48, 
		XorAssign=49, TildeAssign=50, ORG=51, Question=52, SingleQuote=53, Quote=54, 
		Colon=55, Comma=56, Pound=57, AT=58, CRLF=59, SegmentType=60, DataType=61, 
		Number=62, Identifier=63, StringLiteral=64, WS=65, COMMENT=66;
	public const int
		RULE_asmFile = 0, RULE_codeLine = 1, RULE_directive = 2, RULE_moduleName = 3, 
		RULE_sdccOpts = 4, RULE_segment = 5, RULE_segmentName = 6, RULE_segmentOpts = 7, 
		RULE_bootAddr = 8, RULE_memoryAlloc = 9, RULE_memoryData = 10, RULE_ifStatement = 11, 
		RULE_label = 12, RULE_statement = 13, RULE_absAddrAllocExpr = 14, RULE_instruction = 15, 
		RULE_expressions = 16, RULE_expr = 17, RULE_operand = 18, RULE_operator = 19, 
		RULE_arithmeticOperator = 20, RULE_unaryOperator = 21, RULE_assignmentOperator = 22, 
		RULE_bitOperator = 23, RULE_compareOperator = 24, RULE_logicalOperator = 25, 
		RULE_normalLabel = 26, RULE_inlineLabel = 27;
	public static readonly string[] ruleNames = {
		"asmFile", "codeLine", "directive", "moduleName", "sdccOpts", "segment", 
		"segmentName", "segmentOpts", "bootAddr", "memoryAlloc", "memoryData", 
		"ifStatement", "label", "statement", "absAddrAllocExpr", "instruction", 
		"expressions", "expr", "operand", "operator", "arithmeticOperator", "unaryOperator", 
		"assignmentOperator", "bitOperator", "compareOperator", "logicalOperator", 
		"normalLabel", "inlineLabel"
	};

	private static readonly string[] _LiteralNames = {
		null, "'16bit'", "'24bit'", "'32bit'", "'module'", "'optsdcc'", "'local'", 
		"'$'", "'.if'", "'.ifdef'", "'.else'", "'.endif'", "'\\'", "'=:'", "'.'", 
		"'('", "')'", "'['", "']'", "'<'", "'<='", "'>'", "'>='", "'=='", "'!='", 
		"'-'", "'+'", "'*'", "'/'", "'%'", "'&&'", "'||'", "'!'", "'<<'", "'>>'", 
		"'&'", "'|'", "'^'", "'~'", "'='", "'+='", "'-='", "'*='", "'/='", "'%='", 
		"'<<='", "'>>='", "'&='", "'|='", "'^='", "'~='", "'org'", "'?'", "'''", 
		"'\"'", "':'", "','", "'#'", "'@'"
	};
	private static readonly string[] _SymbolicNames = {
		null, null, null, null, null, null, null, null, null, null, null, null, 
		null, null, "Dot", "LeftParen", "RightParen", "LeftBracket", "RightBracket", 
		"Less", "LessEqual", "Greater", "GreaterEqual", "Equal", "NotEqual", "Minus", 
		"Plus", "Star", "Div", "Mod", "AndAnd", "OrOr", "Not", "LeftShift", "RightShift", 
		"And", "Or", "Caret", "Tilde", "Assign", "PlusAssign", "MinusAssign", 
		"StarAssign", "DivAssign", "ModAssign", "LeftShiftAssign", "RightShiftAssign", 
		"AndAssign", "OrAssign", "XorAssign", "TildeAssign", "ORG", "Question", 
		"SingleQuote", "Quote", "Colon", "Comma", "Pound", "AT", "CRLF", "SegmentType", 
		"DataType", "Number", "Identifier", "StringLiteral", "WS", "COMMENT"
	};
	public static readonly IVocabulary DefaultVocabulary = new Vocabulary(_LiteralNames, _SymbolicNames);

	[NotNull]
	public override IVocabulary Vocabulary
	{
		get
		{
			return DefaultVocabulary;
		}
	}

	public override string GrammarFileName { get { return "SdAsm.g4"; } }

	public override string[] RuleNames { get { return ruleNames; } }

	public override int[] SerializedAtn { get { return _serializedATN; } }

	static SdAsmParser() {
		decisionToDFA = new DFA[_ATN.NumberOfDecisions];
		for (int i = 0; i < _ATN.NumberOfDecisions; i++) {
			decisionToDFA[i] = new DFA(_ATN.GetDecisionState(i), i);
		}
	}

		public SdAsmParser(ITokenStream input) : this(input, Console.Out, Console.Error) { }

		public SdAsmParser(ITokenStream input, TextWriter output, TextWriter errorOutput)
		: base(input, output, errorOutput)
	{
		Interpreter = new ParserATNSimulator(this, _ATN, decisionToDFA, sharedContextCache);
	}

	public partial class AsmFileContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode Eof() { return GetToken(SdAsmParser.Eof, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] CRLF() { return GetTokens(SdAsmParser.CRLF); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode CRLF(int i) {
			return GetToken(SdAsmParser.CRLF, i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public CodeLineContext[] codeLine() {
			return GetRuleContexts<CodeLineContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public CodeLineContext codeLine(int i) {
			return GetRuleContext<CodeLineContext>(i);
		}
		public AsmFileContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_asmFile; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			ISdAsmListener typedListener = listener as ISdAsmListener;
			if (typedListener != null) typedListener.EnterAsmFile(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			ISdAsmListener typedListener = listener as ISdAsmListener;
			if (typedListener != null) typedListener.ExitAsmFile(this);
		}
	}

	[RuleVersion(0)]
	public AsmFileContext asmFile() {
		AsmFileContext _localctx = new AsmFileContext(Context, State);
		EnterRule(_localctx, 0, RULE_asmFile);
		int _la;
		try {
			State = 78;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,3,Context) ) {
			case 1:
				EnterOuterAlt(_localctx, 1);
				{
				State = 59;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
				while (_la==CRLF) {
					{
					{
					State = 56;
					Match(CRLF);
					}
					}
					State = 61;
					ErrorHandler.Sync(this);
					_la = TokenStream.LA(1);
				}
				State = 70;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
				while ((((_la) & ~0x3f) == 0 && ((1L << _la) & ((1L << T__7) | (1L << T__8) | (1L << T__9) | (1L << T__10) | (1L << Dot) | (1L << Number) | (1L << Identifier))) != 0)) {
					{
					{
					State = 62;
					codeLine();
					State = 64;
					ErrorHandler.Sync(this);
					_la = TokenStream.LA(1);
					do {
						{
						{
						State = 63;
						Match(CRLF);
						}
						}
						State = 66;
						ErrorHandler.Sync(this);
						_la = TokenStream.LA(1);
					} while ( _la==CRLF );
					}
					}
					State = 72;
					ErrorHandler.Sync(this);
					_la = TokenStream.LA(1);
				}
				State = 73;
				Match(Eof);
				}
				break;
			case 2:
				EnterOuterAlt(_localctx, 2);
				{
				State = 74;
				codeLine();
				State = 75;
				Match(Eof);
				}
				break;
			case 3:
				EnterOuterAlt(_localctx, 3);
				{
				State = 77;
				Match(Eof);
				}
				break;
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class CodeLineContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public DirectiveContext directive() {
			return GetRuleContext<DirectiveContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public SegmentContext segment() {
			return GetRuleContext<SegmentContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public BootAddrContext bootAddr() {
			return GetRuleContext<BootAddrContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public MemoryAllocContext memoryAlloc() {
			return GetRuleContext<MemoryAllocContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public IfStatementContext ifStatement() {
			return GetRuleContext<IfStatementContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public LabelContext label() {
			return GetRuleContext<LabelContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public StatementContext statement() {
			return GetRuleContext<StatementContext>(0);
		}
		public CodeLineContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_codeLine; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			ISdAsmListener typedListener = listener as ISdAsmListener;
			if (typedListener != null) typedListener.EnterCodeLine(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			ISdAsmListener typedListener = listener as ISdAsmListener;
			if (typedListener != null) typedListener.ExitCodeLine(this);
		}
	}

	[RuleVersion(0)]
	public CodeLineContext codeLine() {
		CodeLineContext _localctx = new CodeLineContext(Context, State);
		EnterRule(_localctx, 2, RULE_codeLine);
		try {
			State = 87;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,4,Context) ) {
			case 1:
				EnterOuterAlt(_localctx, 1);
				{
				State = 80;
				directive();
				}
				break;
			case 2:
				EnterOuterAlt(_localctx, 2);
				{
				State = 81;
				segment();
				}
				break;
			case 3:
				EnterOuterAlt(_localctx, 3);
				{
				State = 82;
				bootAddr();
				}
				break;
			case 4:
				EnterOuterAlt(_localctx, 4);
				{
				State = 83;
				memoryAlloc();
				}
				break;
			case 5:
				EnterOuterAlt(_localctx, 5);
				{
				State = 84;
				ifStatement();
				}
				break;
			case 6:
				EnterOuterAlt(_localctx, 6);
				{
				State = 85;
				label();
				}
				break;
			case 7:
				EnterOuterAlt(_localctx, 7);
				{
				State = 86;
				statement();
				}
				break;
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class DirectiveContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode Dot() { return GetToken(SdAsmParser.Dot, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ModuleNameContext moduleName() {
			return GetRuleContext<ModuleNameContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public SdccOptsContext[] sdccOpts() {
			return GetRuleContexts<SdccOptsContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public SdccOptsContext sdccOpts(int i) {
			return GetRuleContext<SdccOptsContext>(i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] Identifier() { return GetTokens(SdAsmParser.Identifier); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode Identifier(int i) {
			return GetToken(SdAsmParser.Identifier, i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] Comma() { return GetTokens(SdAsmParser.Comma); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode Comma(int i) {
			return GetToken(SdAsmParser.Comma, i);
		}
		public DirectiveContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_directive; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			ISdAsmListener typedListener = listener as ISdAsmListener;
			if (typedListener != null) typedListener.EnterDirective(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			ISdAsmListener typedListener = listener as ISdAsmListener;
			if (typedListener != null) typedListener.ExitDirective(this);
		}
	}

	[RuleVersion(0)]
	public DirectiveContext directive() {
		DirectiveContext _localctx = new DirectiveContext(Context, State);
		EnterRule(_localctx, 4, RULE_directive);
		int _la;
		try {
			State = 111;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,7,Context) ) {
			case 1:
				EnterOuterAlt(_localctx, 1);
				{
				State = 89;
				Match(Dot);
				State = 90;
				_la = TokenStream.LA(1);
				if ( !((((_la) & ~0x3f) == 0 && ((1L << _la) & ((1L << T__0) | (1L << T__1) | (1L << T__2))) != 0)) ) {
				ErrorHandler.RecoverInline(this);
				}
				else {
					ErrorHandler.ReportMatch(this);
				    Consume();
				}
				}
				break;
			case 2:
				EnterOuterAlt(_localctx, 2);
				{
				State = 91;
				Match(Dot);
				State = 92;
				Match(T__3);
				State = 93;
				moduleName();
				}
				break;
			case 3:
				EnterOuterAlt(_localctx, 3);
				{
				State = 94;
				Match(Dot);
				State = 95;
				Match(T__4);
				State = 97;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
				do {
					{
					{
					State = 96;
					sdccOpts();
					}
					}
					State = 99;
					ErrorHandler.Sync(this);
					_la = TokenStream.LA(1);
				} while ( _la==Minus );
				}
				break;
			case 4:
				EnterOuterAlt(_localctx, 4);
				{
				State = 101;
				Match(Dot);
				State = 102;
				Match(T__5);
				State = 103;
				Match(Identifier);
				State = 108;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
				while (_la==Comma) {
					{
					{
					State = 104;
					Match(Comma);
					State = 105;
					Match(Identifier);
					}
					}
					State = 110;
					ErrorHandler.Sync(this);
					_la = TokenStream.LA(1);
				}
				}
				break;
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ModuleNameContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] Identifier() { return GetTokens(SdAsmParser.Identifier); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode Identifier(int i) {
			return GetToken(SdAsmParser.Identifier, i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] Number() { return GetTokens(SdAsmParser.Number); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode Number(int i) {
			return GetToken(SdAsmParser.Number, i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] Minus() { return GetTokens(SdAsmParser.Minus); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode Minus(int i) {
			return GetToken(SdAsmParser.Minus, i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] Pound() { return GetTokens(SdAsmParser.Pound); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode Pound(int i) {
			return GetToken(SdAsmParser.Pound, i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] AT() { return GetTokens(SdAsmParser.AT); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode AT(int i) {
			return GetToken(SdAsmParser.AT, i);
		}
		public ModuleNameContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_moduleName; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			ISdAsmListener typedListener = listener as ISdAsmListener;
			if (typedListener != null) typedListener.EnterModuleName(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			ISdAsmListener typedListener = listener as ISdAsmListener;
			if (typedListener != null) typedListener.ExitModuleName(this);
		}
	}

	[RuleVersion(0)]
	public ModuleNameContext moduleName() {
		ModuleNameContext _localctx = new ModuleNameContext(Context, State);
		EnterRule(_localctx, 6, RULE_moduleName);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 114;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			do {
				{
				{
				State = 113;
				_la = TokenStream.LA(1);
				if ( !((((_la) & ~0x3f) == 0 && ((1L << _la) & ((1L << Minus) | (1L << Pound) | (1L << AT) | (1L << Number) | (1L << Identifier))) != 0)) ) {
				ErrorHandler.RecoverInline(this);
				}
				else {
					ErrorHandler.ReportMatch(this);
				    Consume();
				}
				}
				}
				State = 116;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			} while ( (((_la) & ~0x3f) == 0 && ((1L << _la) & ((1L << Minus) | (1L << Pound) | (1L << AT) | (1L << Number) | (1L << Identifier))) != 0) );
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class SdccOptsContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode Identifier() { return GetToken(SdAsmParser.Identifier, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] Minus() { return GetTokens(SdAsmParser.Minus); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode Minus(int i) {
			return GetToken(SdAsmParser.Minus, i);
		}
		public SdccOptsContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_sdccOpts; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			ISdAsmListener typedListener = listener as ISdAsmListener;
			if (typedListener != null) typedListener.EnterSdccOpts(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			ISdAsmListener typedListener = listener as ISdAsmListener;
			if (typedListener != null) typedListener.ExitSdccOpts(this);
		}
	}

	[RuleVersion(0)]
	public SdccOptsContext sdccOpts() {
		SdccOptsContext _localctx = new SdccOptsContext(Context, State);
		EnterRule(_localctx, 8, RULE_sdccOpts);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 119;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			do {
				{
				{
				State = 118;
				Match(Minus);
				}
				}
				State = 121;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			} while ( _la==Minus );
			State = 123;
			Match(Identifier);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class SegmentContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode Dot() { return GetToken(SdAsmParser.Dot, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode SegmentType() { return GetToken(SdAsmParser.SegmentType, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public SegmentNameContext segmentName() {
			return GetRuleContext<SegmentNameContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode LeftParen() { return GetToken(SdAsmParser.LeftParen, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public SegmentOptsContext[] segmentOpts() {
			return GetRuleContexts<SegmentOptsContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public SegmentOptsContext segmentOpts(int i) {
			return GetRuleContext<SegmentOptsContext>(i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode RightParen() { return GetToken(SdAsmParser.RightParen, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] Comma() { return GetTokens(SdAsmParser.Comma); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode Comma(int i) {
			return GetToken(SdAsmParser.Comma, i);
		}
		public SegmentContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_segment; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			ISdAsmListener typedListener = listener as ISdAsmListener;
			if (typedListener != null) typedListener.EnterSegment(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			ISdAsmListener typedListener = listener as ISdAsmListener;
			if (typedListener != null) typedListener.ExitSegment(this);
		}
	}

	[RuleVersion(0)]
	public SegmentContext segment() {
		SegmentContext _localctx = new SegmentContext(Context, State);
		EnterRule(_localctx, 10, RULE_segment);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 125;
			Match(Dot);
			State = 126;
			Match(SegmentType);
			State = 127;
			segmentName();
			State = 139;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			if (_la==LeftParen) {
				{
				State = 128;
				Match(LeftParen);
				State = 129;
				segmentOpts();
				State = 134;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
				while (_la==Comma) {
					{
					{
					State = 130;
					Match(Comma);
					State = 131;
					segmentOpts();
					}
					}
					State = 136;
					ErrorHandler.Sync(this);
					_la = TokenStream.LA(1);
				}
				State = 137;
				Match(RightParen);
				}
			}

			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class SegmentNameContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode Identifier() { return GetToken(SdAsmParser.Identifier, 0); }
		public SegmentNameContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_segmentName; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			ISdAsmListener typedListener = listener as ISdAsmListener;
			if (typedListener != null) typedListener.EnterSegmentName(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			ISdAsmListener typedListener = listener as ISdAsmListener;
			if (typedListener != null) typedListener.ExitSegmentName(this);
		}
	}

	[RuleVersion(0)]
	public SegmentNameContext segmentName() {
		SegmentNameContext _localctx = new SegmentNameContext(Context, State);
		EnterRule(_localctx, 12, RULE_segmentName);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 141;
			Match(Identifier);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class SegmentOptsContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] Identifier() { return GetTokens(SdAsmParser.Identifier); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode Identifier(int i) {
			return GetToken(SdAsmParser.Identifier, i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode Assign() { return GetToken(SdAsmParser.Assign, 0); }
		public SegmentOptsContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_segmentOpts; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			ISdAsmListener typedListener = listener as ISdAsmListener;
			if (typedListener != null) typedListener.EnterSegmentOpts(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			ISdAsmListener typedListener = listener as ISdAsmListener;
			if (typedListener != null) typedListener.ExitSegmentOpts(this);
		}
	}

	[RuleVersion(0)]
	public SegmentOptsContext segmentOpts() {
		SegmentOptsContext _localctx = new SegmentOptsContext(Context, State);
		EnterRule(_localctx, 14, RULE_segmentOpts);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 143;
			Match(Identifier);
			State = 146;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			if (_la==Assign) {
				{
				State = 144;
				Match(Assign);
				State = 145;
				Match(Identifier);
				}
			}

			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class BootAddrContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode Dot() { return GetToken(SdAsmParser.Dot, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode ORG() { return GetToken(SdAsmParser.ORG, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode Number() { return GetToken(SdAsmParser.Number, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ExpressionsContext expressions() {
			return GetRuleContext<ExpressionsContext>(0);
		}
		public BootAddrContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_bootAddr; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			ISdAsmListener typedListener = listener as ISdAsmListener;
			if (typedListener != null) typedListener.EnterBootAddr(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			ISdAsmListener typedListener = listener as ISdAsmListener;
			if (typedListener != null) typedListener.ExitBootAddr(this);
		}
	}

	[RuleVersion(0)]
	public BootAddrContext bootAddr() {
		BootAddrContext _localctx = new BootAddrContext(Context, State);
		EnterRule(_localctx, 16, RULE_bootAddr);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 148;
			Match(Dot);
			State = 149;
			Match(ORG);
			State = 152;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,13,Context) ) {
			case 1:
				{
				State = 150;
				Match(Number);
				}
				break;
			case 2:
				{
				State = 151;
				expressions();
				}
				break;
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class MemoryAllocContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode Dot() { return GetToken(SdAsmParser.Dot, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode DataType() { return GetToken(SdAsmParser.DataType, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public MemoryDataContext[] memoryData() {
			return GetRuleContexts<MemoryDataContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public MemoryDataContext memoryData(int i) {
			return GetRuleContext<MemoryDataContext>(i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] Comma() { return GetTokens(SdAsmParser.Comma); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode Comma(int i) {
			return GetToken(SdAsmParser.Comma, i);
		}
		public MemoryAllocContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_memoryAlloc; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			ISdAsmListener typedListener = listener as ISdAsmListener;
			if (typedListener != null) typedListener.EnterMemoryAlloc(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			ISdAsmListener typedListener = listener as ISdAsmListener;
			if (typedListener != null) typedListener.ExitMemoryAlloc(this);
		}
	}

	[RuleVersion(0)]
	public MemoryAllocContext memoryAlloc() {
		MemoryAllocContext _localctx = new MemoryAllocContext(Context, State);
		EnterRule(_localctx, 18, RULE_memoryAlloc);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 154;
			Match(Dot);
			State = 155;
			Match(DataType);
			State = 156;
			memoryData();
			State = 161;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			while (_la==Comma) {
				{
				{
				State = 157;
				Match(Comma);
				State = 158;
				memoryData();
				}
				}
				State = 163;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class MemoryDataContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode Number() { return GetToken(SdAsmParser.Number, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode StringLiteral() { return GetToken(SdAsmParser.StringLiteral, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode LeftParen() { return GetToken(SdAsmParser.LeftParen, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ExprContext expr() {
			return GetRuleContext<ExprContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode RightParen() { return GetToken(SdAsmParser.RightParen, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode Pound() { return GetToken(SdAsmParser.Pound, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode Identifier() { return GetToken(SdAsmParser.Identifier, 0); }
		public MemoryDataContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_memoryData; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			ISdAsmListener typedListener = listener as ISdAsmListener;
			if (typedListener != null) typedListener.EnterMemoryData(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			ISdAsmListener typedListener = listener as ISdAsmListener;
			if (typedListener != null) typedListener.ExitMemoryData(this);
		}
	}

	[RuleVersion(0)]
	public MemoryDataContext memoryData() {
		MemoryDataContext _localctx = new MemoryDataContext(Context, State);
		EnterRule(_localctx, 20, RULE_memoryData);
		int _la;
		try {
			State = 177;
			ErrorHandler.Sync(this);
			switch (TokenStream.LA(1)) {
			case Number:
				EnterOuterAlt(_localctx, 1);
				{
				State = 164;
				Match(Number);
				State = 166;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
				if (_la==T__6) {
					{
					State = 165;
					Match(T__6);
					}
				}

				}
				break;
			case StringLiteral:
				EnterOuterAlt(_localctx, 2);
				{
				State = 168;
				Match(StringLiteral);
				}
				break;
			case LeftParen:
			case Pound:
				EnterOuterAlt(_localctx, 3);
				{
				State = 170;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
				if (_la==Pound) {
					{
					State = 169;
					Match(Pound);
					}
				}

				State = 172;
				Match(LeftParen);
				State = 173;
				expr(0);
				State = 174;
				Match(RightParen);
				}
				break;
			case Identifier:
				EnterOuterAlt(_localctx, 4);
				{
				State = 176;
				Match(Identifier);
				}
				break;
			default:
				throw new NoViableAltException(this);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class IfStatementContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode Identifier() { return GetToken(SdAsmParser.Identifier, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode Not() { return GetToken(SdAsmParser.Not, 0); }
		public IfStatementContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_ifStatement; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			ISdAsmListener typedListener = listener as ISdAsmListener;
			if (typedListener != null) typedListener.EnterIfStatement(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			ISdAsmListener typedListener = listener as ISdAsmListener;
			if (typedListener != null) typedListener.ExitIfStatement(this);
		}
	}

	[RuleVersion(0)]
	public IfStatementContext ifStatement() {
		IfStatementContext _localctx = new IfStatementContext(Context, State);
		EnterRule(_localctx, 22, RULE_ifStatement);
		int _la;
		try {
			State = 188;
			ErrorHandler.Sync(this);
			switch (TokenStream.LA(1)) {
			case T__7:
				EnterOuterAlt(_localctx, 1);
				{
				State = 179;
				Match(T__7);
				State = 181;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
				if (_la==Not) {
					{
					State = 180;
					Match(Not);
					}
				}

				State = 183;
				Match(Identifier);
				}
				break;
			case T__8:
				EnterOuterAlt(_localctx, 2);
				{
				State = 184;
				Match(T__8);
				State = 185;
				Match(Identifier);
				}
				break;
			case T__9:
				EnterOuterAlt(_localctx, 3);
				{
				State = 186;
				Match(T__9);
				}
				break;
			case T__10:
				EnterOuterAlt(_localctx, 4);
				{
				State = 187;
				Match(T__10);
				}
				break;
			default:
				throw new NoViableAltException(this);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class LabelContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public NormalLabelContext normalLabel() {
			return GetRuleContext<NormalLabelContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public InlineLabelContext inlineLabel() {
			return GetRuleContext<InlineLabelContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] Colon() { return GetTokens(SdAsmParser.Colon); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode Colon(int i) {
			return GetToken(SdAsmParser.Colon, i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public CodeLineContext codeLine() {
			return GetRuleContext<CodeLineContext>(0);
		}
		public LabelContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_label; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			ISdAsmListener typedListener = listener as ISdAsmListener;
			if (typedListener != null) typedListener.EnterLabel(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			ISdAsmListener typedListener = listener as ISdAsmListener;
			if (typedListener != null) typedListener.ExitLabel(this);
		}
	}

	[RuleVersion(0)]
	public LabelContext label() {
		LabelContext _localctx = new LabelContext(Context, State);
		EnterRule(_localctx, 24, RULE_label);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 192;
			ErrorHandler.Sync(this);
			switch (TokenStream.LA(1)) {
			case Dot:
			case Identifier:
				{
				State = 190;
				normalLabel();
				}
				break;
			case Number:
				{
				State = 191;
				inlineLabel();
				}
				break;
			default:
				throw new NoViableAltException(this);
			}
			State = 195;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			do {
				{
				{
				State = 194;
				Match(Colon);
				}
				}
				State = 197;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			} while ( _la==Colon );
			State = 200;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			if ((((_la) & ~0x3f) == 0 && ((1L << _la) & ((1L << T__7) | (1L << T__8) | (1L << T__9) | (1L << T__10) | (1L << Dot) | (1L << Number) | (1L << Identifier))) != 0)) {
				{
				State = 199;
				codeLine();
				}
			}

			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class StatementContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public AbsAddrAllocExprContext absAddrAllocExpr() {
			return GetRuleContext<AbsAddrAllocExprContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public InstructionContext instruction() {
			return GetRuleContext<InstructionContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ExpressionsContext expressions() {
			return GetRuleContext<ExpressionsContext>(0);
		}
		public StatementContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_statement; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			ISdAsmListener typedListener = listener as ISdAsmListener;
			if (typedListener != null) typedListener.EnterStatement(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			ISdAsmListener typedListener = listener as ISdAsmListener;
			if (typedListener != null) typedListener.ExitStatement(this);
		}
	}

	[RuleVersion(0)]
	public StatementContext statement() {
		StatementContext _localctx = new StatementContext(Context, State);
		EnterRule(_localctx, 26, RULE_statement);
		int _la;
		try {
			State = 207;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,24,Context) ) {
			case 1:
				EnterOuterAlt(_localctx, 1);
				{
				State = 202;
				absAddrAllocExpr();
				}
				break;
			case 2:
				EnterOuterAlt(_localctx, 2);
				{
				State = 203;
				instruction();
				State = 205;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
				if ((((_la) & ~0x3f) == 0 && ((1L << _la) & ((1L << T__11) | (1L << Dot) | (1L << LeftParen) | (1L << Less) | (1L << Greater) | (1L << Minus) | (1L << Plus) | (1L << Tilde) | (1L << SingleQuote) | (1L << Quote) | (1L << Pound) | (1L << AT) | (1L << Number) | (1L << Identifier))) != 0)) {
					{
					State = 204;
					expressions();
					}
				}

				}
				break;
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class AbsAddrAllocExprContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode Identifier() { return GetToken(SdAsmParser.Identifier, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public AssignmentOperatorContext assignmentOperator() {
			return GetRuleContext<AssignmentOperatorContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode Number() { return GetToken(SdAsmParser.Number, 0); }
		public AbsAddrAllocExprContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_absAddrAllocExpr; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			ISdAsmListener typedListener = listener as ISdAsmListener;
			if (typedListener != null) typedListener.EnterAbsAddrAllocExpr(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			ISdAsmListener typedListener = listener as ISdAsmListener;
			if (typedListener != null) typedListener.ExitAbsAddrAllocExpr(this);
		}
	}

	[RuleVersion(0)]
	public AbsAddrAllocExprContext absAddrAllocExpr() {
		AbsAddrAllocExprContext _localctx = new AbsAddrAllocExprContext(Context, State);
		EnterRule(_localctx, 28, RULE_absAddrAllocExpr);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 209;
			Match(Identifier);
			State = 210;
			assignmentOperator();
			State = 211;
			Match(Number);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class InstructionContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode Identifier() { return GetToken(SdAsmParser.Identifier, 0); }
		public InstructionContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_instruction; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			ISdAsmListener typedListener = listener as ISdAsmListener;
			if (typedListener != null) typedListener.EnterInstruction(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			ISdAsmListener typedListener = listener as ISdAsmListener;
			if (typedListener != null) typedListener.ExitInstruction(this);
		}
	}

	[RuleVersion(0)]
	public InstructionContext instruction() {
		InstructionContext _localctx = new InstructionContext(Context, State);
		EnterRule(_localctx, 30, RULE_instruction);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 213;
			Match(Identifier);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ExpressionsContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ExprContext[] expr() {
			return GetRuleContexts<ExprContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public ExprContext expr(int i) {
			return GetRuleContext<ExprContext>(i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] Comma() { return GetTokens(SdAsmParser.Comma); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode Comma(int i) {
			return GetToken(SdAsmParser.Comma, i);
		}
		public ExpressionsContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_expressions; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			ISdAsmListener typedListener = listener as ISdAsmListener;
			if (typedListener != null) typedListener.EnterExpressions(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			ISdAsmListener typedListener = listener as ISdAsmListener;
			if (typedListener != null) typedListener.ExitExpressions(this);
		}
	}

	[RuleVersion(0)]
	public ExpressionsContext expressions() {
		ExpressionsContext _localctx = new ExpressionsContext(Context, State);
		EnterRule(_localctx, 32, RULE_expressions);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 215;
			expr(0);
			State = 220;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			while (_la==Comma) {
				{
				{
				State = 216;
				Match(Comma);
				State = 217;
				expr(0);
				}
				}
				State = 222;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ExprContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public OperandContext operand() {
			return GetRuleContext<OperandContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode Plus() { return GetToken(SdAsmParser.Plus, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode Minus() { return GetToken(SdAsmParser.Minus, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode Tilde() { return GetToken(SdAsmParser.Tilde, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public UnaryOperatorContext unaryOperator() {
			return GetRuleContext<UnaryOperatorContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode Dot() { return GetToken(SdAsmParser.Dot, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode Number() { return GetToken(SdAsmParser.Number, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode LeftParen() { return GetToken(SdAsmParser.LeftParen, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode RightParen() { return GetToken(SdAsmParser.RightParen, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode Pound() { return GetToken(SdAsmParser.Pound, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ExpressionsContext[] expressions() {
			return GetRuleContexts<ExpressionsContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public ExpressionsContext expressions(int i) {
			return GetRuleContext<ExpressionsContext>(i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ExprContext[] expr() {
			return GetRuleContexts<ExprContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public ExprContext expr(int i) {
			return GetRuleContext<ExprContext>(i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public OperatorContext @operator() {
			return GetRuleContext<OperatorContext>(0);
		}
		public ExprContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_expr; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			ISdAsmListener typedListener = listener as ISdAsmListener;
			if (typedListener != null) typedListener.EnterExpr(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			ISdAsmListener typedListener = listener as ISdAsmListener;
			if (typedListener != null) typedListener.ExitExpr(this);
		}
	}

	[RuleVersion(0)]
	public ExprContext expr() {
		return expr(0);
	}

	private ExprContext expr(int _p) {
		ParserRuleContext _parentctx = Context;
		int _parentState = State;
		ExprContext _localctx = new ExprContext(Context, _parentState);
		ExprContext _prevctx = _localctx;
		int _startState = 34;
		EnterRecursionRule(_localctx, 34, RULE_expr, _p);
		int _la;
		try {
			int _alt;
			EnterOuterAlt(_localctx, 1);
			{
			State = 252;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,31,Context) ) {
			case 1:
				{
				State = 228;
				ErrorHandler.Sync(this);
				switch (TokenStream.LA(1)) {
				case Plus:
					{
					State = 224;
					Match(Plus);
					}
					break;
				case Minus:
					{
					State = 225;
					Match(Minus);
					}
					break;
				case Tilde:
					{
					State = 226;
					Match(Tilde);
					}
					break;
				case T__11:
				case Less:
				case Greater:
				case SingleQuote:
				case Quote:
					{
					State = 227;
					unaryOperator();
					}
					break;
				default:
					throw new NoViableAltException(this);
				}
				State = 230;
				operand();
				}
				break;
			case 2:
				{
				State = 231;
				operand();
				State = 234;
				ErrorHandler.Sync(this);
				switch ( Interpreter.AdaptivePredict(TokenStream,27,Context) ) {
				case 1:
					{
					State = 232;
					Match(Dot);
					State = 233;
					Match(Number);
					}
					break;
				}
				}
				break;
			case 3:
				{
				State = 242;
				ErrorHandler.Sync(this);
				switch (TokenStream.LA(1)) {
				case Pound:
					{
					State = 236;
					Match(Pound);
					State = 238;
					ErrorHandler.Sync(this);
					_la = TokenStream.LA(1);
					if ((((_la) & ~0x3f) == 0 && ((1L << _la) & ((1L << T__11) | (1L << Less) | (1L << Greater) | (1L << SingleQuote) | (1L << Quote))) != 0)) {
						{
						State = 237;
						unaryOperator();
						}
					}

					}
					break;
				case T__11:
				case Less:
				case Greater:
				case SingleQuote:
				case Quote:
					{
					State = 240;
					unaryOperator();
					}
					break;
				case Number:
					{
					State = 241;
					Match(Number);
					}
					break;
				case LeftParen:
					break;
				default:
					break;
				}
				State = 244;
				Match(LeftParen);
				State = 246;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
				do {
					{
					{
					State = 245;
					expressions();
					}
					}
					State = 248;
					ErrorHandler.Sync(this);
					_la = TokenStream.LA(1);
				} while ( (((_la) & ~0x3f) == 0 && ((1L << _la) & ((1L << T__11) | (1L << Dot) | (1L << LeftParen) | (1L << Less) | (1L << Greater) | (1L << Minus) | (1L << Plus) | (1L << Tilde) | (1L << SingleQuote) | (1L << Quote) | (1L << Pound) | (1L << AT) | (1L << Number) | (1L << Identifier))) != 0) );
				State = 250;
				Match(RightParen);
				}
				break;
			}
			Context.Stop = TokenStream.LT(-1);
			State = 260;
			ErrorHandler.Sync(this);
			_alt = Interpreter.AdaptivePredict(TokenStream,32,Context);
			while ( _alt!=2 && _alt!=global::Antlr4.Runtime.Atn.ATN.INVALID_ALT_NUMBER ) {
				if ( _alt==1 ) {
					if ( ParseListeners!=null )
						TriggerExitRuleEvent();
					_prevctx = _localctx;
					{
					{
					_localctx = new ExprContext(_parentctx, _parentState);
					PushNewRecursionContext(_localctx, _startState, RULE_expr);
					State = 254;
					if (!(Precpred(Context, 4))) throw new FailedPredicateException(this, "Precpred(Context, 4)");
					State = 255;
					@operator();
					State = 256;
					expr(5);
					}
					} 
				}
				State = 262;
				ErrorHandler.Sync(this);
				_alt = Interpreter.AdaptivePredict(TokenStream,32,Context);
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			UnrollRecursionContexts(_parentctx);
		}
		return _localctx;
	}

	public partial class OperandContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode Number() { return GetToken(SdAsmParser.Number, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public NormalLabelContext normalLabel() {
			return GetRuleContext<NormalLabelContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public InlineLabelContext inlineLabel() {
			return GetRuleContext<InlineLabelContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode Pound() { return GetToken(SdAsmParser.Pound, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode AT() { return GetToken(SdAsmParser.AT, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode Dot() { return GetToken(SdAsmParser.Dot, 0); }
		public OperandContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_operand; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			ISdAsmListener typedListener = listener as ISdAsmListener;
			if (typedListener != null) typedListener.EnterOperand(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			ISdAsmListener typedListener = listener as ISdAsmListener;
			if (typedListener != null) typedListener.ExitOperand(this);
		}
	}

	[RuleVersion(0)]
	public OperandContext operand() {
		OperandContext _localctx = new OperandContext(Context, State);
		EnterRule(_localctx, 36, RULE_operand);
		int _la;
		try {
			State = 275;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,36,Context) ) {
			case 1:
				EnterOuterAlt(_localctx, 1);
				{
				State = 263;
				Match(Number);
				}
				break;
			case 2:
				EnterOuterAlt(_localctx, 2);
				{
				State = 265;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
				if (_la==Pound) {
					{
					State = 264;
					Match(Pound);
					}
				}

				State = 268;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
				if (_la==AT) {
					{
					State = 267;
					Match(AT);
					}
				}

				State = 272;
				ErrorHandler.Sync(this);
				switch (TokenStream.LA(1)) {
				case Dot:
				case Identifier:
					{
					State = 270;
					normalLabel();
					}
					break;
				case Number:
					{
					State = 271;
					inlineLabel();
					}
					break;
				default:
					throw new NoViableAltException(this);
				}
				}
				break;
			case 3:
				EnterOuterAlt(_localctx, 3);
				{
				State = 274;
				Match(Dot);
				}
				break;
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class OperatorContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ArithmeticOperatorContext arithmeticOperator() {
			return GetRuleContext<ArithmeticOperatorContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public UnaryOperatorContext unaryOperator() {
			return GetRuleContext<UnaryOperatorContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public BitOperatorContext bitOperator() {
			return GetRuleContext<BitOperatorContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public CompareOperatorContext compareOperator() {
			return GetRuleContext<CompareOperatorContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public LogicalOperatorContext logicalOperator() {
			return GetRuleContext<LogicalOperatorContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public AssignmentOperatorContext assignmentOperator() {
			return GetRuleContext<AssignmentOperatorContext>(0);
		}
		public OperatorContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_operator; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			ISdAsmListener typedListener = listener as ISdAsmListener;
			if (typedListener != null) typedListener.EnterOperator(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			ISdAsmListener typedListener = listener as ISdAsmListener;
			if (typedListener != null) typedListener.ExitOperator(this);
		}
	}

	[RuleVersion(0)]
	public OperatorContext @operator() {
		OperatorContext _localctx = new OperatorContext(Context, State);
		EnterRule(_localctx, 38, RULE_operator);
		try {
			State = 283;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,37,Context) ) {
			case 1:
				EnterOuterAlt(_localctx, 1);
				{
				State = 277;
				arithmeticOperator();
				}
				break;
			case 2:
				EnterOuterAlt(_localctx, 2);
				{
				State = 278;
				unaryOperator();
				}
				break;
			case 3:
				EnterOuterAlt(_localctx, 3);
				{
				State = 279;
				bitOperator();
				}
				break;
			case 4:
				EnterOuterAlt(_localctx, 4);
				{
				State = 280;
				compareOperator();
				}
				break;
			case 5:
				EnterOuterAlt(_localctx, 5);
				{
				State = 281;
				logicalOperator();
				}
				break;
			case 6:
				EnterOuterAlt(_localctx, 6);
				{
				State = 282;
				assignmentOperator();
				}
				break;
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ArithmeticOperatorContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode Plus() { return GetToken(SdAsmParser.Plus, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode Minus() { return GetToken(SdAsmParser.Minus, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode Star() { return GetToken(SdAsmParser.Star, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode Div() { return GetToken(SdAsmParser.Div, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode Mod() { return GetToken(SdAsmParser.Mod, 0); }
		public ArithmeticOperatorContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_arithmeticOperator; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			ISdAsmListener typedListener = listener as ISdAsmListener;
			if (typedListener != null) typedListener.EnterArithmeticOperator(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			ISdAsmListener typedListener = listener as ISdAsmListener;
			if (typedListener != null) typedListener.ExitArithmeticOperator(this);
		}
	}

	[RuleVersion(0)]
	public ArithmeticOperatorContext arithmeticOperator() {
		ArithmeticOperatorContext _localctx = new ArithmeticOperatorContext(Context, State);
		EnterRule(_localctx, 40, RULE_arithmeticOperator);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 285;
			_la = TokenStream.LA(1);
			if ( !((((_la) & ~0x3f) == 0 && ((1L << _la) & ((1L << Minus) | (1L << Plus) | (1L << Star) | (1L << Div) | (1L << Mod))) != 0)) ) {
			ErrorHandler.RecoverInline(this);
			}
			else {
				ErrorHandler.ReportMatch(this);
			    Consume();
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class UnaryOperatorContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode Less() { return GetToken(SdAsmParser.Less, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode Greater() { return GetToken(SdAsmParser.Greater, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode SingleQuote() { return GetToken(SdAsmParser.SingleQuote, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode Quote() { return GetToken(SdAsmParser.Quote, 0); }
		public UnaryOperatorContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_unaryOperator; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			ISdAsmListener typedListener = listener as ISdAsmListener;
			if (typedListener != null) typedListener.EnterUnaryOperator(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			ISdAsmListener typedListener = listener as ISdAsmListener;
			if (typedListener != null) typedListener.ExitUnaryOperator(this);
		}
	}

	[RuleVersion(0)]
	public UnaryOperatorContext unaryOperator() {
		UnaryOperatorContext _localctx = new UnaryOperatorContext(Context, State);
		EnterRule(_localctx, 42, RULE_unaryOperator);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 287;
			_la = TokenStream.LA(1);
			if ( !((((_la) & ~0x3f) == 0 && ((1L << _la) & ((1L << T__11) | (1L << Less) | (1L << Greater) | (1L << SingleQuote) | (1L << Quote))) != 0)) ) {
			ErrorHandler.RecoverInline(this);
			}
			else {
				ErrorHandler.ReportMatch(this);
			    Consume();
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class AssignmentOperatorContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode Assign() { return GetToken(SdAsmParser.Assign, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode Equal() { return GetToken(SdAsmParser.Equal, 0); }
		public AssignmentOperatorContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_assignmentOperator; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			ISdAsmListener typedListener = listener as ISdAsmListener;
			if (typedListener != null) typedListener.EnterAssignmentOperator(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			ISdAsmListener typedListener = listener as ISdAsmListener;
			if (typedListener != null) typedListener.ExitAssignmentOperator(this);
		}
	}

	[RuleVersion(0)]
	public AssignmentOperatorContext assignmentOperator() {
		AssignmentOperatorContext _localctx = new AssignmentOperatorContext(Context, State);
		EnterRule(_localctx, 44, RULE_assignmentOperator);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 289;
			_la = TokenStream.LA(1);
			if ( !((((_la) & ~0x3f) == 0 && ((1L << _la) & ((1L << T__12) | (1L << Equal) | (1L << Assign))) != 0)) ) {
			ErrorHandler.RecoverInline(this);
			}
			else {
				ErrorHandler.ReportMatch(this);
			    Consume();
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class BitOperatorContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode LeftShift() { return GetToken(SdAsmParser.LeftShift, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode RightShift() { return GetToken(SdAsmParser.RightShift, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode And() { return GetToken(SdAsmParser.And, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode Or() { return GetToken(SdAsmParser.Or, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode Tilde() { return GetToken(SdAsmParser.Tilde, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode Caret() { return GetToken(SdAsmParser.Caret, 0); }
		public BitOperatorContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_bitOperator; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			ISdAsmListener typedListener = listener as ISdAsmListener;
			if (typedListener != null) typedListener.EnterBitOperator(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			ISdAsmListener typedListener = listener as ISdAsmListener;
			if (typedListener != null) typedListener.ExitBitOperator(this);
		}
	}

	[RuleVersion(0)]
	public BitOperatorContext bitOperator() {
		BitOperatorContext _localctx = new BitOperatorContext(Context, State);
		EnterRule(_localctx, 46, RULE_bitOperator);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 291;
			_la = TokenStream.LA(1);
			if ( !((((_la) & ~0x3f) == 0 && ((1L << _la) & ((1L << LeftShift) | (1L << RightShift) | (1L << And) | (1L << Or) | (1L << Caret) | (1L << Tilde))) != 0)) ) {
			ErrorHandler.RecoverInline(this);
			}
			else {
				ErrorHandler.ReportMatch(this);
			    Consume();
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class CompareOperatorContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode NotEqual() { return GetToken(SdAsmParser.NotEqual, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode Greater() { return GetToken(SdAsmParser.Greater, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode GreaterEqual() { return GetToken(SdAsmParser.GreaterEqual, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode Less() { return GetToken(SdAsmParser.Less, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode LessEqual() { return GetToken(SdAsmParser.LessEqual, 0); }
		public CompareOperatorContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_compareOperator; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			ISdAsmListener typedListener = listener as ISdAsmListener;
			if (typedListener != null) typedListener.EnterCompareOperator(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			ISdAsmListener typedListener = listener as ISdAsmListener;
			if (typedListener != null) typedListener.ExitCompareOperator(this);
		}
	}

	[RuleVersion(0)]
	public CompareOperatorContext compareOperator() {
		CompareOperatorContext _localctx = new CompareOperatorContext(Context, State);
		EnterRule(_localctx, 48, RULE_compareOperator);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 293;
			_la = TokenStream.LA(1);
			if ( !((((_la) & ~0x3f) == 0 && ((1L << _la) & ((1L << Less) | (1L << LessEqual) | (1L << Greater) | (1L << GreaterEqual) | (1L << NotEqual))) != 0)) ) {
			ErrorHandler.RecoverInline(this);
			}
			else {
				ErrorHandler.ReportMatch(this);
			    Consume();
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class LogicalOperatorContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode AndAnd() { return GetToken(SdAsmParser.AndAnd, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode OrOr() { return GetToken(SdAsmParser.OrOr, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode Not() { return GetToken(SdAsmParser.Not, 0); }
		public LogicalOperatorContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_logicalOperator; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			ISdAsmListener typedListener = listener as ISdAsmListener;
			if (typedListener != null) typedListener.EnterLogicalOperator(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			ISdAsmListener typedListener = listener as ISdAsmListener;
			if (typedListener != null) typedListener.ExitLogicalOperator(this);
		}
	}

	[RuleVersion(0)]
	public LogicalOperatorContext logicalOperator() {
		LogicalOperatorContext _localctx = new LogicalOperatorContext(Context, State);
		EnterRule(_localctx, 50, RULE_logicalOperator);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 295;
			_la = TokenStream.LA(1);
			if ( !((((_la) & ~0x3f) == 0 && ((1L << _la) & ((1L << AndAnd) | (1L << OrOr) | (1L << Not))) != 0)) ) {
			ErrorHandler.RecoverInline(this);
			}
			else {
				ErrorHandler.ReportMatch(this);
			    Consume();
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class NormalLabelContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode Identifier() { return GetToken(SdAsmParser.Identifier, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode Dot() { return GetToken(SdAsmParser.Dot, 0); }
		public NormalLabelContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_normalLabel; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			ISdAsmListener typedListener = listener as ISdAsmListener;
			if (typedListener != null) typedListener.EnterNormalLabel(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			ISdAsmListener typedListener = listener as ISdAsmListener;
			if (typedListener != null) typedListener.ExitNormalLabel(this);
		}
	}

	[RuleVersion(0)]
	public NormalLabelContext normalLabel() {
		NormalLabelContext _localctx = new NormalLabelContext(Context, State);
		EnterRule(_localctx, 52, RULE_normalLabel);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 298;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			if (_la==Dot) {
				{
				State = 297;
				Match(Dot);
				}
			}

			State = 300;
			Match(Identifier);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class InlineLabelContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode Number() { return GetToken(SdAsmParser.Number, 0); }
		public InlineLabelContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_inlineLabel; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			ISdAsmListener typedListener = listener as ISdAsmListener;
			if (typedListener != null) typedListener.EnterInlineLabel(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			ISdAsmListener typedListener = listener as ISdAsmListener;
			if (typedListener != null) typedListener.ExitInlineLabel(this);
		}
	}

	[RuleVersion(0)]
	public InlineLabelContext inlineLabel() {
		InlineLabelContext _localctx = new InlineLabelContext(Context, State);
		EnterRule(_localctx, 54, RULE_inlineLabel);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 302;
			Match(Number);
			State = 303;
			Match(T__6);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public override bool Sempred(RuleContext _localctx, int ruleIndex, int predIndex) {
		switch (ruleIndex) {
		case 17: return expr_sempred((ExprContext)_localctx, predIndex);
		}
		return true;
	}
	private bool expr_sempred(ExprContext _localctx, int predIndex) {
		switch (predIndex) {
		case 0: return Precpred(Context, 4);
		}
		return true;
	}

	private static int[] _serializedATN = {
		4,1,66,306,2,0,7,0,2,1,7,1,2,2,7,2,2,3,7,3,2,4,7,4,2,5,7,5,2,6,7,6,2,7,
		7,7,2,8,7,8,2,9,7,9,2,10,7,10,2,11,7,11,2,12,7,12,2,13,7,13,2,14,7,14,
		2,15,7,15,2,16,7,16,2,17,7,17,2,18,7,18,2,19,7,19,2,20,7,20,2,21,7,21,
		2,22,7,22,2,23,7,23,2,24,7,24,2,25,7,25,2,26,7,26,2,27,7,27,1,0,5,0,58,
		8,0,10,0,12,0,61,9,0,1,0,1,0,4,0,65,8,0,11,0,12,0,66,5,0,69,8,0,10,0,12,
		0,72,9,0,1,0,1,0,1,0,1,0,1,0,3,0,79,8,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,3,
		1,88,8,1,1,2,1,2,1,2,1,2,1,2,1,2,1,2,1,2,4,2,98,8,2,11,2,12,2,99,1,2,1,
		2,1,2,1,2,1,2,5,2,107,8,2,10,2,12,2,110,9,2,3,2,112,8,2,1,3,4,3,115,8,
		3,11,3,12,3,116,1,4,4,4,120,8,4,11,4,12,4,121,1,4,1,4,1,5,1,5,1,5,1,5,
		1,5,1,5,1,5,5,5,133,8,5,10,5,12,5,136,9,5,1,5,1,5,3,5,140,8,5,1,6,1,6,
		1,7,1,7,1,7,3,7,147,8,7,1,8,1,8,1,8,1,8,3,8,153,8,8,1,9,1,9,1,9,1,9,1,
		9,5,9,160,8,9,10,9,12,9,163,9,9,1,10,1,10,3,10,167,8,10,1,10,1,10,3,10,
		171,8,10,1,10,1,10,1,10,1,10,1,10,3,10,178,8,10,1,11,1,11,3,11,182,8,11,
		1,11,1,11,1,11,1,11,1,11,3,11,189,8,11,1,12,1,12,3,12,193,8,12,1,12,4,
		12,196,8,12,11,12,12,12,197,1,12,3,12,201,8,12,1,13,1,13,1,13,3,13,206,
		8,13,3,13,208,8,13,1,14,1,14,1,14,1,14,1,15,1,15,1,16,1,16,1,16,5,16,219,
		8,16,10,16,12,16,222,9,16,1,17,1,17,1,17,1,17,1,17,3,17,229,8,17,1,17,
		1,17,1,17,1,17,3,17,235,8,17,1,17,1,17,3,17,239,8,17,1,17,1,17,3,17,243,
		8,17,1,17,1,17,4,17,247,8,17,11,17,12,17,248,1,17,1,17,3,17,253,8,17,1,
		17,1,17,1,17,1,17,5,17,259,8,17,10,17,12,17,262,9,17,1,18,1,18,3,18,266,
		8,18,1,18,3,18,269,8,18,1,18,1,18,3,18,273,8,18,1,18,3,18,276,8,18,1,19,
		1,19,1,19,1,19,1,19,1,19,3,19,284,8,19,1,20,1,20,1,21,1,21,1,22,1,22,1,
		23,1,23,1,24,1,24,1,25,1,25,1,26,3,26,299,8,26,1,26,1,26,1,27,1,27,1,27,
		1,27,0,1,34,28,0,2,4,6,8,10,12,14,16,18,20,22,24,26,28,30,32,34,36,38,
		40,42,44,46,48,50,52,54,0,8,1,0,1,3,3,0,25,25,57,58,62,63,1,0,25,29,4,
		0,12,12,19,19,21,21,53,54,3,0,13,13,23,23,39,39,1,0,33,38,2,0,19,22,24,
		24,1,0,30,32,338,0,78,1,0,0,0,2,87,1,0,0,0,4,111,1,0,0,0,6,114,1,0,0,0,
		8,119,1,0,0,0,10,125,1,0,0,0,12,141,1,0,0,0,14,143,1,0,0,0,16,148,1,0,
		0,0,18,154,1,0,0,0,20,177,1,0,0,0,22,188,1,0,0,0,24,192,1,0,0,0,26,207,
		1,0,0,0,28,209,1,0,0,0,30,213,1,0,0,0,32,215,1,0,0,0,34,252,1,0,0,0,36,
		275,1,0,0,0,38,283,1,0,0,0,40,285,1,0,0,0,42,287,1,0,0,0,44,289,1,0,0,
		0,46,291,1,0,0,0,48,293,1,0,0,0,50,295,1,0,0,0,52,298,1,0,0,0,54,302,1,
		0,0,0,56,58,5,59,0,0,57,56,1,0,0,0,58,61,1,0,0,0,59,57,1,0,0,0,59,60,1,
		0,0,0,60,70,1,0,0,0,61,59,1,0,0,0,62,64,3,2,1,0,63,65,5,59,0,0,64,63,1,
		0,0,0,65,66,1,0,0,0,66,64,1,0,0,0,66,67,1,0,0,0,67,69,1,0,0,0,68,62,1,
		0,0,0,69,72,1,0,0,0,70,68,1,0,0,0,70,71,1,0,0,0,71,73,1,0,0,0,72,70,1,
		0,0,0,73,79,5,0,0,1,74,75,3,2,1,0,75,76,5,0,0,1,76,79,1,0,0,0,77,79,5,
		0,0,1,78,59,1,0,0,0,78,74,1,0,0,0,78,77,1,0,0,0,79,1,1,0,0,0,80,88,3,4,
		2,0,81,88,3,10,5,0,82,88,3,16,8,0,83,88,3,18,9,0,84,88,3,22,11,0,85,88,
		3,24,12,0,86,88,3,26,13,0,87,80,1,0,0,0,87,81,1,0,0,0,87,82,1,0,0,0,87,
		83,1,0,0,0,87,84,1,0,0,0,87,85,1,0,0,0,87,86,1,0,0,0,88,3,1,0,0,0,89,90,
		5,14,0,0,90,112,7,0,0,0,91,92,5,14,0,0,92,93,5,4,0,0,93,112,3,6,3,0,94,
		95,5,14,0,0,95,97,5,5,0,0,96,98,3,8,4,0,97,96,1,0,0,0,98,99,1,0,0,0,99,
		97,1,0,0,0,99,100,1,0,0,0,100,112,1,0,0,0,101,102,5,14,0,0,102,103,5,6,
		0,0,103,108,5,63,0,0,104,105,5,56,0,0,105,107,5,63,0,0,106,104,1,0,0,0,
		107,110,1,0,0,0,108,106,1,0,0,0,108,109,1,0,0,0,109,112,1,0,0,0,110,108,
		1,0,0,0,111,89,1,0,0,0,111,91,1,0,0,0,111,94,1,0,0,0,111,101,1,0,0,0,112,
		5,1,0,0,0,113,115,7,1,0,0,114,113,1,0,0,0,115,116,1,0,0,0,116,114,1,0,
		0,0,116,117,1,0,0,0,117,7,1,0,0,0,118,120,5,25,0,0,119,118,1,0,0,0,120,
		121,1,0,0,0,121,119,1,0,0,0,121,122,1,0,0,0,122,123,1,0,0,0,123,124,5,
		63,0,0,124,9,1,0,0,0,125,126,5,14,0,0,126,127,5,60,0,0,127,139,3,12,6,
		0,128,129,5,15,0,0,129,134,3,14,7,0,130,131,5,56,0,0,131,133,3,14,7,0,
		132,130,1,0,0,0,133,136,1,0,0,0,134,132,1,0,0,0,134,135,1,0,0,0,135,137,
		1,0,0,0,136,134,1,0,0,0,137,138,5,16,0,0,138,140,1,0,0,0,139,128,1,0,0,
		0,139,140,1,0,0,0,140,11,1,0,0,0,141,142,5,63,0,0,142,13,1,0,0,0,143,146,
		5,63,0,0,144,145,5,39,0,0,145,147,5,63,0,0,146,144,1,0,0,0,146,147,1,0,
		0,0,147,15,1,0,0,0,148,149,5,14,0,0,149,152,5,51,0,0,150,153,5,62,0,0,
		151,153,3,32,16,0,152,150,1,0,0,0,152,151,1,0,0,0,153,17,1,0,0,0,154,155,
		5,14,0,0,155,156,5,61,0,0,156,161,3,20,10,0,157,158,5,56,0,0,158,160,3,
		20,10,0,159,157,1,0,0,0,160,163,1,0,0,0,161,159,1,0,0,0,161,162,1,0,0,
		0,162,19,1,0,0,0,163,161,1,0,0,0,164,166,5,62,0,0,165,167,5,7,0,0,166,
		165,1,0,0,0,166,167,1,0,0,0,167,178,1,0,0,0,168,178,5,64,0,0,169,171,5,
		57,0,0,170,169,1,0,0,0,170,171,1,0,0,0,171,172,1,0,0,0,172,173,5,15,0,
		0,173,174,3,34,17,0,174,175,5,16,0,0,175,178,1,0,0,0,176,178,5,63,0,0,
		177,164,1,0,0,0,177,168,1,0,0,0,177,170,1,0,0,0,177,176,1,0,0,0,178,21,
		1,0,0,0,179,181,5,8,0,0,180,182,5,32,0,0,181,180,1,0,0,0,181,182,1,0,0,
		0,182,183,1,0,0,0,183,189,5,63,0,0,184,185,5,9,0,0,185,189,5,63,0,0,186,
		189,5,10,0,0,187,189,5,11,0,0,188,179,1,0,0,0,188,184,1,0,0,0,188,186,
		1,0,0,0,188,187,1,0,0,0,189,23,1,0,0,0,190,193,3,52,26,0,191,193,3,54,
		27,0,192,190,1,0,0,0,192,191,1,0,0,0,193,195,1,0,0,0,194,196,5,55,0,0,
		195,194,1,0,0,0,196,197,1,0,0,0,197,195,1,0,0,0,197,198,1,0,0,0,198,200,
		1,0,0,0,199,201,3,2,1,0,200,199,1,0,0,0,200,201,1,0,0,0,201,25,1,0,0,0,
		202,208,3,28,14,0,203,205,3,30,15,0,204,206,3,32,16,0,205,204,1,0,0,0,
		205,206,1,0,0,0,206,208,1,0,0,0,207,202,1,0,0,0,207,203,1,0,0,0,208,27,
		1,0,0,0,209,210,5,63,0,0,210,211,3,44,22,0,211,212,5,62,0,0,212,29,1,0,
		0,0,213,214,5,63,0,0,214,31,1,0,0,0,215,220,3,34,17,0,216,217,5,56,0,0,
		217,219,3,34,17,0,218,216,1,0,0,0,219,222,1,0,0,0,220,218,1,0,0,0,220,
		221,1,0,0,0,221,33,1,0,0,0,222,220,1,0,0,0,223,228,6,17,-1,0,224,229,5,
		26,0,0,225,229,5,25,0,0,226,229,5,38,0,0,227,229,3,42,21,0,228,224,1,0,
		0,0,228,225,1,0,0,0,228,226,1,0,0,0,228,227,1,0,0,0,229,230,1,0,0,0,230,
		253,3,36,18,0,231,234,3,36,18,0,232,233,5,14,0,0,233,235,5,62,0,0,234,
		232,1,0,0,0,234,235,1,0,0,0,235,253,1,0,0,0,236,238,5,57,0,0,237,239,3,
		42,21,0,238,237,1,0,0,0,238,239,1,0,0,0,239,243,1,0,0,0,240,243,3,42,21,
		0,241,243,5,62,0,0,242,236,1,0,0,0,242,240,1,0,0,0,242,241,1,0,0,0,242,
		243,1,0,0,0,243,244,1,0,0,0,244,246,5,15,0,0,245,247,3,32,16,0,246,245,
		1,0,0,0,247,248,1,0,0,0,248,246,1,0,0,0,248,249,1,0,0,0,249,250,1,0,0,
		0,250,251,5,16,0,0,251,253,1,0,0,0,252,223,1,0,0,0,252,231,1,0,0,0,252,
		242,1,0,0,0,253,260,1,0,0,0,254,255,10,4,0,0,255,256,3,38,19,0,256,257,
		3,34,17,5,257,259,1,0,0,0,258,254,1,0,0,0,259,262,1,0,0,0,260,258,1,0,
		0,0,260,261,1,0,0,0,261,35,1,0,0,0,262,260,1,0,0,0,263,276,5,62,0,0,264,
		266,5,57,0,0,265,264,1,0,0,0,265,266,1,0,0,0,266,268,1,0,0,0,267,269,5,
		58,0,0,268,267,1,0,0,0,268,269,1,0,0,0,269,272,1,0,0,0,270,273,3,52,26,
		0,271,273,3,54,27,0,272,270,1,0,0,0,272,271,1,0,0,0,273,276,1,0,0,0,274,
		276,5,14,0,0,275,263,1,0,0,0,275,265,1,0,0,0,275,274,1,0,0,0,276,37,1,
		0,0,0,277,284,3,40,20,0,278,284,3,42,21,0,279,284,3,46,23,0,280,284,3,
		48,24,0,281,284,3,50,25,0,282,284,3,44,22,0,283,277,1,0,0,0,283,278,1,
		0,0,0,283,279,1,0,0,0,283,280,1,0,0,0,283,281,1,0,0,0,283,282,1,0,0,0,
		284,39,1,0,0,0,285,286,7,2,0,0,286,41,1,0,0,0,287,288,7,3,0,0,288,43,1,
		0,0,0,289,290,7,4,0,0,290,45,1,0,0,0,291,292,7,5,0,0,292,47,1,0,0,0,293,
		294,7,6,0,0,294,49,1,0,0,0,295,296,7,7,0,0,296,51,1,0,0,0,297,299,5,14,
		0,0,298,297,1,0,0,0,298,299,1,0,0,0,299,300,1,0,0,0,300,301,5,63,0,0,301,
		53,1,0,0,0,302,303,5,62,0,0,303,304,5,7,0,0,304,55,1,0,0,0,39,59,66,70,
		78,87,99,108,111,116,121,134,139,146,152,161,166,170,177,181,188,192,197,
		200,205,207,220,228,234,238,242,248,252,260,265,268,272,275,283,298
	};

	public static readonly ATN _ATN =
		new ATNDeserializer().Deserialize(_serializedATN);


}
